In [1]:
import pandas as pd
import os

In [2]:
file_path = r"01_District_wise_crimes_committed_IPC_2001_2012.csv"

df = pd.read_csv(file_path)

In [3]:
df.columns = df.columns.str.strip().str.upper()

required_columns = [
    "STATE/UT",
    "DISTRICT",
    "MURDER",
    "RAPE",
    "THEFT",
    "DOWRY DEATHS"
]

missing = [col for col in required_columns if col not in df.columns]

if missing:
    print("Missing columns:", missing)
else:
    print("All required columns found.")

All required columns found.

In [4]:
df = df.dropna()

numeric_columns = [
    "MURDER",
    "RAPE",
    "THEFT",
    "DOWRY DEATHS"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.dropna()

df["STATE/UT"] = df["STATE/UT"].astype(str).str.strip()
df["DISTRICT"] = df["DISTRICT"].astype(str).str.strip()

In [5]:
os.makedirs("../backend/clean_datasets", exist_ok=True)

save_path = "../backend/clean_datasets/cleaned_crime_data.csv"

df.to_csv(save_path, index=False)

print("Saved successfully.")

Saved successfully.

In [6]:
import pandas as pd
import numpy as np
import os

In [7]:
def clean_dataset(input_path, output_name):

    print(f"\nCleaning: {output_name}")

    df = pd.read_csv(input_path)

    # STANDARDIZE COLUMN NAMES
    df.columns = (
        df.columns
        .str.strip()
        .str.upper()
        .str.replace("_", " ")
    )

    # REMOVE DUPLICATES
    df = df.drop_duplicates()

    # CONVERT POSSIBLE NUMERIC COLUMNS
    for col in df.columns:

        try:
            df[col] = pd.to_numeric(df[col])
        except:
            pass

    # REMOVE FULLY EMPTY ROWS
    df = df.dropna(how="all")

    # FILL REMAINING NULLS
    numeric_cols = df.select_dtypes(include=np.number).columns

    for col in numeric_cols:
        df[col] = df[col].fillna(df[col].median())

    text_cols = df.select_dtypes(include="object").columns

    for col in text_cols:
        df[col] = (
            df[col]
            .astype(str)
            .str.strip()
        )

    # REMOVE UNNAMED COLUMNS
    df = df.loc[:, ~df.columns.str.contains("^UNNAMED")]

    # SAVE CLEANED DATASET
    save_folder = "../backend/clean_datasets"

    os.makedirs(save_folder, exist_ok=True)

    save_path = f"{save_folder}/{output_name}"

    df.to_csv(save_path, index=False)

    print("Saved:", save_path)

    print("Shape:", df.shape)

    print("Columns:")
    print(df.columns.tolist())

    return df

In [ ]:
clean_dataset(
    r"C:/Users/SHREYA/Desktop/Crime-In-India-Project/backend/notebooks/01_District_wise_crimes_committed_IPC_2001_2012.csv",
    "cleaned_ipc.csv"
)

NameError: name 'clean_dataset' is not defined

In [17]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\02_01_District_wise_crimes_committed_against_SC_2001_2012.csv",
    "cleaned_st.csv"
)

Cleaning: cleaned_st.csv
Saved: ../backend/clean_datasets/cleaned_st.csv
Shape: (9016, 13)
Columns:
['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'RAPE', 'KIDNAPPING AND ABDUCTION', 'DACOITY', 'ROBBERY', 'ARSON', 'HURT', 'PREVENTION OF ATROCITIES (POA) ACT', 'PROTECTION OF CIVIL RIGHTS (PCR) ACT', 'OTHER CRIMES AGAINST SCS']

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,STATE/UT,DISTRICT,YEAR,MURDER,RAPE,KIDNAPPING AND ABDUCTION,DACOITY,ROBBERY,ARSON,HURT,PREVENTION OF ATROCITIES (POA) ACT,PROTECTION OF CIVIL RIGHTS (PCR) ACT,OTHER CRIMES AGAINST SCS
0,ANDHRA PRADESH,ADILABAD,2001,0,1,4,0,0,0,3,0,15,32
1,ANDHRA PRADESH,ANANTAPUR,2001,0,4,0,0,0,0,49,21,0,53
2,ANDHRA PRADESH,CHITTOOR,2001,3,3,0,0,0,0,38,36,0,34
3,ANDHRA PRADESH,CUDDAPAH,2001,0,3,0,0,0,0,20,52,0,25
4,ANDHRA PRADESH,EAST GODAVARI,2001,1,3,0,0,0,0,3,12,63,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9013,LAKSHADWEEP,LAKSHADWEEP,2012,0,0,0,0,0,0,0,0,0,0
9014,LAKSHADWEEP,TOTAL,2012,0,0,0,0,0,0,0,0,0,0
9015,PUDUCHERRY,KARAIKAL,2012,1,0,0,0,0,0,0,0,0,0
9016,PUDUCHERRY,PUDUCHERRY,2012,1,0,0,0,0,0,0,1,20,1
9017,PUDUCHERRY,TOTAL,2012,2,0,0,0,0,0,0,1,20,1

In [2]:
import pandas as pd

# LOAD FILE

df = pd.read_csv(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\clean_datasets\cleaned_st.csv"
)

# RENAME COLUMNS
# IMPORTANT:
# We are ONLY standardizing names

df = df.rename(columns={

    "KIDNAPPING AND ABDUCTION": "KIDNAPPING",

    "ROBBERY": "THEFT"

})

# SAVE FINAL STANDARDIZED FILE

df.to_csv(

    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\clean_datasets\st_standardized.csv",

    index=False

)

# CHECK RESULT

print("ST standardized saved")
print(df.columns.tolist())
print("Shape:", df.shape)

ST standardized saved
['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'RAPE', 'KIDNAPPING', 'DACOITY', 'THEFT', 'ARSON', 'HURT', 'PREVENTION OF ATROCITIES (POA) ACT', 'PROTECTION OF CIVIL RIGHTS (PCR) ACT', 'OTHER CRIMES AGAINST SCS']
Shape: (9016, 13)

In [18]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\02_District_wise_crimes_committed_against_ST_2001_2012.csv",
    "cleaned_sc.csv"
)

Cleaning: cleaned_sc.csv
Saved: ../backend/clean_datasets/cleaned_sc.csv
Shape: (9016, 13)
Columns:
['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'RAPE', 'KIDNAPPING ABDUCTION', 'DACOITY', 'ROBBERY', 'ARSON', 'HURT', 'PROTECTION OF CIVIL RIGHTS (PCR) ACT', 'PREVENTION OF ATROCITIES (POA) ACT', 'OTHER CRIMES AGAINST STS']

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,STATE/UT,DISTRICT,YEAR,MURDER,RAPE,KIDNAPPING ABDUCTION,DACOITY,ROBBERY,ARSON,HURT,PROTECTION OF CIVIL RIGHTS (PCR) ACT,PREVENTION OF ATROCITIES (POA) ACT,OTHER CRIMES AGAINST STS
0,ANDHRA PRADESH,ADILABAD,2001,0,1,2,0,0,0,2,0,0,13
1,ANDHRA PRADESH,ANANTAPUR,2001,0,0,0,0,0,0,7,0,1,6
2,ANDHRA PRADESH,CHITTOOR,2001,0,0,0,0,0,0,2,0,0,0
3,ANDHRA PRADESH,CUDDAPAH,2001,0,0,0,0,0,0,2,0,2,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,0,0,0,0,0,0,0,0,0,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9013,LAKSHADWEEP,LAKSHADWEEP,2012,0,0,0,0,0,0,0,0,0,0
9014,LAKSHADWEEP,TOTAL,2012,0,0,0,0,0,0,0,0,0,0
9015,PUDUCHERRY,KARAIKAL,2012,0,0,0,0,0,0,0,0,0,0
9016,PUDUCHERRY,PUDUCHERRY,2012,0,0,0,0,0,0,0,0,0,0
9017,PUDUCHERRY,TOTAL,2012,0,0,0,0,0,0,0,0,0,0

In [19]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\03_District_wise_crimes_committed_against_children_2001_2012.csv",
    "cleaned_children.csv"
)

Cleaning: cleaned_children.csv
Saved: ../backend/clean_datasets/cleaned_children.csv
Shape: (9014, 15)
Columns:
['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'RAPE', 'KIDNAPPING AND ABDUCTION', 'FOETICIDE', 'ABETMENT OF SUICIDE', 'EXPOSURE AND ABANDONMENT', 'PROCURATION OF MINOR GIRLS', 'BUYING OF GIRLS FOR PROSTITUTION', 'SELLING OF GIRLS FOR PROSTITUTION', 'PROHIBITION OF CHILD MARRIAGE ACT', 'OTHER CRIMES', 'TOTAL']

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,STATE/UT,DISTRICT,YEAR,MURDER,RAPE,KIDNAPPING AND ABDUCTION,FOETICIDE,ABETMENT OF SUICIDE,EXPOSURE AND ABANDONMENT,PROCURATION OF MINOR GIRLS,BUYING OF GIRLS FOR PROSTITUTION,SELLING OF GIRLS FOR PROSTITUTION,PROHIBITION OF CHILD MARRIAGE ACT,OTHER CRIMES,TOTAL
0,ANDHRA PRADESH,ADILABAD,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,ANDHRA PRADESH,ANANTAPUR,2001,19.0,12.0,29.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,66
2,ANDHRA PRADESH,CHITTOOR,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,ANDHRA PRADESH,CUDDAPAH,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9010,LAKSHADWEEP,LAKSHADWEEP,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
9011,LAKSHADWEEP,TOTAL,2012,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
9012,PUDUCHERRY,KARAIKAL,2012,0.0,3.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,7
9013,PUDUCHERRY,PUDUCHERRY,2012,0.0,4.0,16.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,2.0,25
9014,PUDUCHERRY,TOTAL,2012,0.0,7.0,18.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,3.0,32

In [20]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\08_01_Juvenile_apprehended_state_IPC_2001_2010.csv",
    "cleaned_juvenile.csv"
)

Cleaning: cleaned_juvenile.csv
Saved: ../backend/clean_datasets/cleaned_juvenile.csv
Shape: (10500, 12)
Columns:
['STATE/UT', 'YEAR', 'CRIME', 'BOYS 7-12 YEARS', 'GIRLS 7-12 YEARS', 'BOYS 12-16 YEARS', 'GIRLS 12-16 YEARS', 'BOYS 16-18 YEARS', 'GIRLS 16-18 YEARS', 'TOTAL FOR BOYS ALL AGE GROUPS', 'TOTAL FOR GIRLS ALL AGE GROUPS', 'GRAND TOTAL']

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,STATE/UT,YEAR,CRIME,BOYS 7-12 YEARS,GIRLS 7-12 YEARS,BOYS 12-16 YEARS,GIRLS 12-16 YEARS,BOYS 16-18 YEARS,GIRLS 16-18 YEARS,TOTAL FOR BOYS ALL AGE GROUPS,TOTAL FOR GIRLS ALL AGE GROUPS,GRAND TOTAL
0,Andhra Pradesh,2001,Murder,3,0,7,0,5,0,15,0,15
1,Andhra Pradesh,2001,Attempt to Commit Murder,2,0,0,0,11,0,13,0,13
2,Andhra Pradesh,2001,C H Not amounting to Murder,0,0,0,0,0,0,0,0,0
3,Andhra Pradesh,2001,Rape,2,0,15,0,2,1,19,1,20
4,Andhra Pradesh,2001,Custodial Rape,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10495,Puducherry,2010,Cruelty by Husband or Relatives,0,0,0,0,0,0,0,0,0
10496,Puducherry,2010,Importation of girls from Foreign Countr,0,0,0,0,0,0,0,0,0
10497,Puducherry,2010,Causing death by negligence,0,0,0,0,0,0,0,0,0
10498,Puducherry,2010,Other IPC Crimes,0,0,1,0,2,3,3,3,6
10499,Puducherry,2010,Total IPC Crimes,0,0,8,0,31,4,39,4,43

In [21]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\11_Property_stolen_and_recovered_nature_of_property_2001_2010.csv",
    "cleaned_property.csv"
)

Cleaning: cleaned_property.csv

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

Saved: ../backend/clean_datasets/cleaned_property.csv
Shape: (4550, 8)
Columns:
['AREA NAME', 'YEAR', 'GROUP NAME', 'SUB GROUP NAME', 'CASES PROPERTY RECOVERED', 'CASES PROPERTY STOLEN', 'VALUE OF PROPERTY RECOVERED', 'VALUE OF PROPERTY STOLEN']

,AREA NAME,YEAR,GROUP NAME,SUB GROUP NAME,CASES PROPERTY RECOVERED,CASES PROPERTY STOLEN,VALUE OF PROPERTY RECOVERED,VALUE OF PROPERTY STOLEN
0,Andaman & Nicobar Islands,2001,Cattle - Property,2. Cattle,0,1,0,1000
1,Andhra Pradesh,2001,Cattle - Property,2. Cattle,448,580,6490596,7233876
2,Arunachal Pradesh,2001,Cattle - Property,2. Cattle,22,34,135500,704500
3,Assam,2001,Cattle - Property,2. Cattle,149,322,683350,1816386
4,Bihar,2001,Cattle - Property,2. Cattle,144,334,896019,1911068
...,...,...,...,...,...,...,...,...
4545,Tamil Nadu,2010,Total Property(Nature),Total Property Stolen & Recovered,16125,21509,660311804,1317919190
4546,Tripura,2010,Total Property(Nature),Total Property Stolen & Recovered,192,879,5666102,33032746
4547,Uttar Pradesh,2010,Total Property(Nature),Total Property Stolen & Recovered,9130,35068,577591772,1442670414
4548,Uttarakhand,2010,Total Property(Nature),Total Property Stolen & Recovered,964,2234,47135685,123398840
4549,West Bengal,2010,Total Property(Nature),Total Property Stolen & Recovered,4548,23759,1168242161,5015168687

In [22]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\13_Police_killed_or_injured_on_duty2001_2010.csv",
    "cleaned_police.csv"
)

Cleaning: cleaned_police.csv
Saved: ../backend/clean_datasets/cleaned_police.csv
Shape: (2450, 18)
Columns:
['AREA NAME', 'YEAR', 'GROUP NAME', 'SUB GROUP NAME', 'POLICE INJURED BY CRIMINALS', 'POLICE INJURED BY RIOTOUS MOBS', 'POLICE INJURED IN ACCIDENTS', 'POLICE INJURED IN DACOITY OPERATIONSOTHER RAIDS', 'POLICE INJURED IN TERRORISTSEXTREMISTS OPERATIONS', 'POLICE INJURED ON BORDER DUTIES', 'POLICE INJURED TOTAL POLICEMEN', 'POLICE KILLED BY CRIMINALS', 'POLICE KILLED BY RIOTOUS MOBS', 'POLICE KILLED IN ACCIDENTS', 'POLICE KILLED IN DACOITY OPERATIONSOTHER RAIDS', 'POLICE KILLED IN TERRORISTSEXTREMISTS OPERATIONS', 'POLICE KILLED ON BORDER DUTIES', 'POLICE KILLED TOTAL POLICEMEN']

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,AREA NAME,YEAR,GROUP NAME,SUB GROUP NAME,POLICE INJURED BY CRIMINALS,POLICE INJURED BY RIOTOUS MOBS,POLICE INJURED IN ACCIDENTS,POLICE INJURED IN DACOITY OPERATIONSOTHER RAIDS,POLICE INJURED IN TERRORISTSEXTREMISTS OPERATIONS,POLICE INJURED ON BORDER DUTIES,POLICE INJURED TOTAL POLICEMEN,POLICE KILLED BY CRIMINALS,POLICE KILLED BY RIOTOUS MOBS,POLICE KILLED IN ACCIDENTS,POLICE KILLED IN DACOITY OPERATIONSOTHER RAIDS,POLICE KILLED IN TERRORISTSEXTREMISTS OPERATIONS,POLICE KILLED ON BORDER DUTIES,POLICE KILLED TOTAL POLICEMEN
0,Andaman & Nicobar Islands,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Andhra Pradesh,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,0,3,4,1,3,0,11,0,0,2,0,3,0,5
2,Arunachal Pradesh,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Assam,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,0,0,0,0,1,0,1,0,0,1,0,0,0,1
4,Bihar,2001,Police - Assistant Sub-Inspectors,3. Assistant Sub-Inspectos,1,0,0,0,2,0,3,0,0,0,0,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2445,Tamil Nadu,2010,Police - Total,7. Total Police Killed or Injured,10,26,142,4,0,0,182,2,0,65,0,0,0,67
2446,Tripura,2010,Police - Total,7. Total Police Killed or Injured,0,0,0,0,2,0,2,0,0,0,0,0,2,2
2447,Uttar Pradesh,2010,Police - Total,7. Total Police Killed or Injured,6,10,9,10,0,8,43,2,1,101,0,0,1,105
2448,Uttarakhand,2010,Police - Total,7. Total Police Killed or Injured,0,0,5,0,0,0,5,0,0,15,0,0,0,15
2449,West Bengal,2010,Police - Total,7. Total Police Killed or Injured,17,265,86,23,21,0,412,2,0,20,1,2,0,25

In [23]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\17_Case_reported_and_value_of_property_taken_away_by_place_of_occurrence_2001_2012.csv",
    "cleaned_property_occurrence.csv"
)

Cleaning: cleaned_property_occurrence.csv
Saved: ../backend/clean_datasets/cleaned_property_occurrence.csv
Shape: (4344, 11)
Columns:
['STATE/UT', 'YEAR', 'PLACE OF OCCURRENCE', 'DACOITY (SECTION 395-398 IPC) - NUMBER OF CASES REGISTERED', 'DACOITY (SECTION 395-398 IPC) - VALUE OF PROPERTY STOLEN (IN RUPEES)', 'ROBBERY(SECTION 392-394, 397, 398 IPC) - NUMBER OF CASES REGISTERED', 'ROBBERY(SECTION 392-394, 397, 398 IPC) - VALUE OF PROPERTY STOLEN (IN RUPEES)', 'BURGLARY(SECTION 449-452, 454, 455, 457-460 IPC) - NUMBER OF CASES REGISTERED', 'BURGLARY(SECTION 449-452, 454, 455, 457-460 IPC) - VALUE OF PROPERTY STOLEN (IN RUPEES)', 'THEFT (SECTION 379-382 IPC) - NUMBER OF CASES REGISTERED', 'THEFT (SECTION 379-382 IPC) - VALUE OF PROPERTY STOLEN (IN RUPEES)']

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,STATE/UT,YEAR,PLACE OF OCCURRENCE,DACOITY (SECTION 395-398 IPC) - NUMBER OF CASES REGISTERED,DACOITY (SECTION 395-398 IPC) - VALUE OF PROPERTY STOLEN (IN RUPEES),"ROBBERY(SECTION 392-394, 397, 398 IPC) - NUMBER OF CASES REGISTERED","ROBBERY(SECTION 392-394, 397, 398 IPC) - VALUE OF PROPERTY STOLEN (IN RUPEES)","BURGLARY(SECTION 449-452, 454, 455, 457-460 IPC) - NUMBER OF CASES REGISTERED","BURGLARY(SECTION 449-452, 454, 455, 457-460 IPC) - VALUE OF PROPERTY STOLEN (IN RUPEES)",THEFT (SECTION 379-382 IPC) - NUMBER OF CASES REGISTERED,THEFT (SECTION 379-382 IPC) - VALUE OF PROPERTY STOLEN (IN RUPEES)
0,Andhra Pradesh,2001,RESIDENTIAL PREMISES,100,4446961,177,5962460,5158,105324332,4257,53517835
1,Andhra Pradesh,2001,HIGH-WAY,57,5340335,172,6364866,31,2000574,74,1593092
2,Andhra Pradesh,2001,RIVER & SEA,2,145345,11,209330,101,1412516,110,1610200
3,Andhra Pradesh,2001,RAILWAYS,8,1750800,19,304336,6,24392,943,16418110
4,Andhra Pradesh,2001,RUNNING TRAINS,5,75000,3,164000,0,0,296,6170175
...,...,...,...,...,...,...,...,...,...,...,...
4339,Puducherry,2012,BANKS,0,0,0,0,0,0,0,0
4340,Puducherry,2012,COMMERCIAL ESTABLISHMENTS,2,58000,4,197230,26,2117964,20,647043
4341,Puducherry,2012,OTHER PLACES,2,575000,8,113100,4,25500,596,19689249
4342,Puducherry,2012,TOTAL (MANUAL),5,683000,16,2520330,77,12168314,658,23866392
4343,Puducherry,2012,TOTAL COMPUTER FROM 1 TO 7,5,683000,16,2520330,77,12168314,658,23866392

In [24]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\17_Crime_by_place_of_occurrence_2001_2012.csv",
    "cleaned_crime_occurrence.csv"
)

Cleaning: cleaned_crime_occurrence.csv
Saved: ../backend/clean_datasets/cleaned_crime_occurrence.csv
Shape: (456, 34)
Columns:
['STATE/UT', 'YEAR', 'RESIDENTIAL PREMISES - DACOITY', 'RESIDENTIAL PREMISES - ROBBERY', 'RESIDENTIAL PREMISES - BURGLARY', 'RESIDENTIAL PREMISES - THEFT', 'HIGHWAYS - DACOITY', 'HIGHWAYS - ROBBERY', 'HIGHWAYS - BURGLARY', 'HIGHWAYS - THEFT', 'RIVER AND SEA - DACOITY', 'RIVER AND SEA - ROBBERY', 'RIVER AND SEA - BURGLARY', 'RIVER AND SEA - THEFT', 'RAILWAYS - DACOITY', 'RAILWAYS - ROBBERY', 'RAILWAYS - BURGLARY', 'RAILWAYS - THEFT', 'BANKS - DACOITY', 'BANKS - ROBBERY', 'BANKS - BURGLARY', 'BANKS - THEFT', 'COMMERCIAL ESTABLISHMENTS - DACOITY', 'COMMERCIAL ESTABLISHMENTS - ROBBERY', 'COMMERCIAL ESTABLISHMENTS - BURGLARY', 'COMMERCIAL ESTABLISHMENTS - THEFT', 'OTHER PLACES - DACOITY', 'OTHER PLACES - ROBBERY', 'OTHER PLACES - BURGLARY', 'OTHER PLACES - THEFT', 'TOTAL - DACOITY', 'TOTAL - ROBBERY', 'TOTAL - BURGLARY', 'TOTAL - THEFT']

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,STATE/UT,YEAR,RESIDENTIAL PREMISES - DACOITY,RESIDENTIAL PREMISES - ROBBERY,RESIDENTIAL PREMISES - BURGLARY,RESIDENTIAL PREMISES - THEFT,HIGHWAYS - DACOITY,HIGHWAYS - ROBBERY,HIGHWAYS - BURGLARY,HIGHWAYS - THEFT,...,COMMERCIAL ESTABLISHMENTS - BURGLARY,COMMERCIAL ESTABLISHMENTS - THEFT,OTHER PLACES - DACOITY,OTHER PLACES - ROBBERY,OTHER PLACES - BURGLARY,OTHER PLACES - THEFT,TOTAL - DACOITY,TOTAL - ROBBERY,TOTAL - BURGLARY,TOTAL - THEFT
0,ANDHRA PRADESH,2001,100,177,5158,4257,57,172,31,74,...,1041,2502,37,232,862,8849,214,629,7220,16751
1,ARUNACHAL PRADESH,2001,9,26,99,131,0,0,0,8,...,84,54,8,40,65,249,22,84,248,443
2,ASSAM,2001,381,191,1695,2901,46,136,7,87,...,442,967,77,261,271,1342,532,687,2423,5367
3,BIHAR,2001,818,326,2486,4741,162,826,0,257,...,231,686,210,880,505,2582,1291,2203,3233,9701
4,CHHATTISGARH,2001,54,42,3336,1417,10,38,12,72,...,370,299,15,239,420,2835,87,338,4144,4812
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,DELHI,2012,10,101,1249,7076,1,32,0,189,...,285,1370,17,431,178,12749,28,608,1715,22032
452,LAKSHADWEEP,2012,0,0,3,7,0,0,0,0,...,0,0,0,0,0,0,0,0,3,7
453,PUDUCHERRY,2012,1,4,47,42,0,0,0,0,...,26,20,2,8,4,596,5,16,77,658
454,TOTAL (UTs),2012,11,123,1515,7974,1,32,0,199,...,412,2042,28,468,217,13554,44,694,2149,24440
455,TOTAL (ALL-INDIA),2012,1288,2821,60698,81861,838,5000,316,27802,...,12228,29661,1797,17480,19154,181277,4314,27343,92892,337407

In [25]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\35_Human_rights_violation_by_police_2001_2010.csv",
    "cleaned_human_rights.csv"
)

Cleaning: cleaned_human_rights.csv
Saved: ../backend/clean_datasets/cleaned_human_rights.csv
Shape: (2267, 7)
Columns:
['AREA NAME', 'YEAR', 'GROUP NAME', 'SUB GROUP NAME', 'CASES REGISTERED UNDER HUMAN RIGHTS VIOLATIONS', 'POLICEMEN CHARGESHEETED', 'POLICEMEN CONVICTED']

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

,AREA NAME,YEAR,GROUP NAME,SUB GROUP NAME,CASES REGISTERED UNDER HUMAN RIGHTS VIOLATIONS,POLICEMEN CHARGESHEETED,POLICEMEN CONVICTED
0,Andhra Pradesh,2001,HR_Disappearance of Persons,01. Disappearance of Persons,0.0,0.0,0.0
1,Arunachal Pradesh,2001,HR_Disappearance of Persons,01. Disappearance of Persons,0.0,0.0,0.0
2,Assam,2001,HR_Disappearance of Persons,01. Disappearance of Persons,0.0,0.0,0.0
3,Bihar,2001,HR_Disappearance of Persons,01. Disappearance of Persons,0.0,0.0,0.0
4,Chandigarh,2001,HR_Disappearance of Persons,01. Disappearance of Persons,0.0,0.0,0.0
...,...,...,...,...,...,...,...
2262,Meghalaya,2010,HR_Total Violations by Police,12. Total (Sum of 1-11 Above),0.0,0.0,0.0
2263,Nagaland,2010,HR_Total Violations by Police,12. Total (Sum of 1-11 Above),0.0,0.0,0.0
2264,Odisha,2010,HR_Total Violations by Police,12. Total (Sum of 1-11 Above),5.0,1.0,0.0
2265,Uttar Pradesh,2010,HR_Total Violations by Police,12. Total (Sum of 1-11 Above),6.0,5.0,0.0
2266,West Bengal,2010,HR_Total Violations by Police,12. Total (Sum of 1-11 Above),1.0,0.0,0.0

In [26]:
clean_dataset(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\notebooks\42_District_wise_crimes_committed_against_women_2001_2012.csv",
    "cleaned_women.csv"
)

Cleaning: cleaned_women.csv

C:\Users\SHREYA\AppData\Local\Temp\ipykernel_13464\2950586198.py:35: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

Saved: ../backend/clean_datasets/cleaned_women.csv
Shape: (9017, 10)
Columns:
['STATE/UT', 'DISTRICT', 'YEAR', 'RAPE', 'KIDNAPPING AND ABDUCTION', 'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY', 'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES', 'IMPORTATION OF GIRLS']

,STATE/UT,DISTRICT,YEAR,RAPE,KIDNAPPING AND ABDUCTION,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS
0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0
...,...,...,...,...,...,...,...,...,...,...
9012,LAKSHADWEEP,LAKSHADWEEP,2012,0,0,0,1,0,1,0
9013,LAKSHADWEEP,TOTAL,2012,0,0,0,1,0,1,0
9014,PUDUCHERRY,KARAIKAL,2012,6,2,0,2,0,1,0
9015,PUDUCHERRY,PUDUCHERRY,2012,7,14,0,7,2,5,0
9016,PUDUCHERRY,TOTAL,2012,13,16,0,9,2,6,0

In [3]:
import pandas as pd

df = pd.read_csv("cleaned_ipc.csv")

print(df.columns.tolist())

FileNotFoundError: [Errno 2] No such file or directory: 'cleaned_ipc.csv'

In [4]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\clean_datasets\cleaned_ipc.csv"
)

print(df.columns.tolist())

['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER', 'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE', 'OTHER RAPE', 'KIDNAPPING & ABDUCTION', 'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS', 'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY', 'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT', 'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST', 'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT', 'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY', 'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES', 'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES', 'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES']

In [5]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\clean_datasets\cleaned_women.csv"
)

print(df.columns.tolist())

['STATE/UT', 'DISTRICT', 'YEAR', 'RAPE', 'KIDNAPPING AND ABDUCTION', 'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY', 'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES', 'IMPORTATION OF GIRLS']

In [ ]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\clean_datasets\cleaned_children.csv"
)

print(df.columns.tolist())

['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'RAPE', 'KIDNAPPING AND ABDUCTION', 'FOETICIDE', 'ABETMENT OF SUICIDE', 'EXPOSURE AND ABANDONMENT', 'PROCURATION OF MINOR GIRLS', 'BUYING OF GIRLS FOR PROSTITUTION', 'SELLING OF GIRLS FOR PROSTITUTION', 'PROHIBITION OF CHILD MARRIAGE ACT', 'OTHER CRIMES', 'TOTAL']

In [7]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\clean_datasets\cleaned_sc.csv"
)

print(df.columns.tolist())

['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'RAPE', 'KIDNAPPING ABDUCTION', 'DACOITY', 'ROBBERY', 'ARSON', 'HURT', 'PROTECTION OF CIVIL RIGHTS (PCR) ACT', 'PREVENTION OF ATROCITIES (POA) ACT', 'OTHER CRIMES AGAINST STS']

In [8]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\SHREYA\Desktop\Crime-In-India-Project\backend\clean_datasets\cleaned_st.csv"
)

print(df.columns.tolist())

['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'RAPE', 'KIDNAPPING AND ABDUCTION', 'DACOITY', 'ROBBERY', 'ARSON', 'HURT', 'PREVENTION OF ATROCITIES (POA) ACT', 'PROTECTION OF CIVIL RIGHTS (PCR) ACT', 'OTHER CRIMES AGAINST SCS']

In [1]:
import pandas as pd
import os

# ====================================================
# FOLDERS
# ====================================================

INPUT_FOLDER = "raw_datasets"
OUTPUT_FOLDER = "clean_datasets"

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# ====================================================
# DATASET CONFIGS
# ====================================================

datasets = [

    {
        "input": "children.csv",
        "output": "children_standardized.csv",

        "rename": {

            "BOYS 7-12 YEARS": "MURDER",
            "GIRLS 7-12 YEARS": "RAPE",
            "BOYS 12-16 YEARS": "KIDNAPPING",
            "BOYS 16-18 YEARS": "THEFT"

        }
    },

    {
        "input": "women.csv",
        "output": "women_standardized.csv",

        "rename": {

            "KIDNAPPING AND ABDUCTION": "KIDNAPPING"

        }
    },

    {
        "input": "ipc.csv",
        "output": "ipc_standardized.csv",

        "rename": {

            "KIDNAPPING & ABDUCTION": "KIDNAPPING"

        }
    },

    {
        "input": "sc.csv",
        "output": "sc_standardized.csv",

        "rename": {

            "KIDNAPPING ABDUCTION": "KIDNAPPING",
            "ROBBERY": "THEFT"

        }
    },

    {
        "input": "st.csv",
        "output": "st_standardized.csv",

        "rename": {

            "KIDNAPPING AND ABDUCTION": "KIDNAPPING",
            "ROBBERY": "THEFT"

        }
    }

]

# ====================================================
# PROCESS
# ====================================================

for dataset in datasets:

    input_path = os.path.join(
        INPUT_FOLDER,
        dataset["input"]
    )

    output_path = os.path.join(
        OUTPUT_FOLDER,
        dataset["output"]
    )

    df = pd.read_csv(input_path)

    # RENAME COLUMNS

    df = df.rename(
        columns=dataset["rename"]
    )

    # SAVE FULL DATASET
    # KEEP ALL COLUMNS

    df.to_csv(
        output_path,
        index=False
    )

    print(
        f"{dataset['output']} saved successfully"
    )

    print(df.columns.tolist())
    print("------------------------------------------------")

FileNotFoundError: [Errno 2] No such file or directory: 'raw_datasets\\children.csv'